### ISSUE TITLE
Fix Arch-Go link in HTML report

### ISSUE THREAD

**Issue by franciscodaines** [fdaines/arch-go#20]
The HTML report contains a broken link in page footer.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/114753578/202722802-2c4dbbcb-c21c-4b8d-bf9a-d6e9a46b569c.png">

The link points to "_arch-go.org_" but this url doesn't exists. It should be replaces to https://github.com/fdaines/arch-go

**Comment by Kanvi1** [comment]
Hi @franciscodaines 
I would like to work on this issue. Can you please assign this to me?
Thanks!

**Comment by fdaines** [comment]
> Hi @franciscodaines I would like to work on this issue. Can you please assign this to me? Thanks!

Great @Kanvi1, thanks for contributing to this project!

**Comment by DGuhr** [comment]
Hey @fdaines  👋 great project! I felt so free and took over this ticket, as there wasn't a PR since Dec 22. See https://github.com/fdaines/arch-go/pull/23 :)

On a sidenote:
I'd love to create a docker image / github action out of arch-go. Or is there already sth out there I am not aware of? 

I could help you to automate creating the docker image and pushing it to a free registry (e.g. Quay.io) and then one could use a [custom docker GHa](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) with an input to the yaml and some flags, to use it in other projects. I effectively would lvoe to use it [here](https://github.com/RedHatInsights/authz) to enforce some architectural constraints (e.g. "domain" package should not rely on any third party library) and make it part of the CI/CD checks :)

**Comment by fdaines** [comment]
Excellent @DGuhr , i've never created a GH action too, so I think that it would be a very useful excercise for both of us!.
